### ISSUE TITLE
Kanban project

### ISSUE THREAD

**Issue by lisandroseia** [lisandroseia/Kanban-lisandro-fernando#16]
[Link to the project](https://github.com/lisandroseia/Kanban-lisandro-fernando/projects/1)

In our team, we are 2 members, Lisandro Seia and  Jose Fernando Herrera

**Comment by Ghiftee** [comment]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @lisandroseia @joseheco 

Good job working on the project so far! 
✔️ Your kanban board is set correctly
However, there are some issues that you need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] The link to your project should be the link to your [kanban board](https://github.com/lisandroseia/Kanban-lisandro-fernando/projects/1) and not the link you currently have. Kindly update it

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by lisandroseia** [comment]
Thanks, we already changed it, we appreciate the feedback

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
